version: 2
jobs:
  build:
    working_directory: ~/pixelgroup-home
    environment:
      IMAGE_TAG: ${CIRCLE_SHA1}
      
    resource_class: small
    parallelism: 2

    # In 2.0, we specify our Ruby version by using a public Docker image
    docker:
       - image: gerey/saasdemo-docker-image:latest

    steps:
      - checkout
      - run: echo "changes"

      - setup_remote_docker:
          reusable: true
      
      - run: docker build -t gerey/pixelgroup-home-uwsgi:${CIRCLE_SHA1} uwsgi
      - run: docker build -t gerey/pixelgroup-home-nginx:${CIRCLE_SHA1} nginx
      

      #push docker image to docker hub
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push gerey/pixelgroup-home-uwsgi:${CIRCLE_SHA1}
      - run: docker push gerey/pixelgroup-home-nginx:${CIRCLE_SHA1}




  test:
    working_directory: ~/pixelgroup-home
    docker:
       - image: gerey/saasdemo-docker-image:latest

    parallelism: 2
    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      # - attach_workspace:
      #   at: /var/lib/docker
      - run: docker pull gerey/pixelgroup-home-uwsgi:${CIRCLE_SHA1}
      - run: docker pull gerey/pixelgroup-home-nginx:${CIRCLE_SHA1}
      - run: docker build -t pixelgroup-home-test test
      - run: xxd -l 8 -p /dev/urandom > test_container_name
      - run: docker-compose -p ${CIRCLE_BUILD_NUM} up -d
      - run: docker run --link ${CIRCLE_BUILD_NUM}_nginx_1:nginx --name $(cat test_container_name) pixelgroup-home-test
     
      - run:
          when: always
          command: |
            mkdir test-reports
            docker cp $(cat test_container_name):/nosetests.xml test-reports/.
            docker-compose kill || true
      
      - store_artifacts:
            path: test-reports

      - store_test_results:
          path: test-reports/

  deploy:
    name: Deploy to ECS
    working_directory: ~/pixelgroup-home
    docker:
      - image: gerey/saasdemo-docker-image:latest
    
    steps:
      - checkout

      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              script/deploy.sh prod
            fi


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
